FROM mitmproxy/mitmproxy

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID


RUN sed -i -e 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
    && apk --update add --no-cache \
    sudo \
    bash

RUN rm -rf /var/cache/apk/*

# 添加用户组
RUN addgroup -g $USER_GID $USERNAME \
    # 添加用户
    && adduser -s /bin/bash -u $USER_UID -G $USERNAME -D $USERNAME \
    # 添加到sudo用户组 使用户可以使用sudo指令
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
