version: "3.7"
services:
  mitmproxy:
    container_name: dev-mitmproxy
    image: mitmproxy/my
    build: .
    volumes:
      - ./.mitmproxy:/home/mitmproxy/.mitmproxy
      # - ~/.ssh:/home/mitmproxy/.ssh:cached
      - .:/work
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode