version: "3"
services:
  dev-py:
    container_name: dev-py
    image: dev:py
    build:
      context: ..
      dockerfile: .devcontainer/Test.Dockerfile
    # args:
    #   USERNAME: vscode
    volumes:
      # - ~/.gitconfig:/root/.gitconfig
      # - ~/.ssh/:/home/root/.ssh/:cached
      - ..:/a1
      - ..:/a2:ro
      - ..:/a3:rw
      - ..:/a4:cached
    # user: vscode
    # working_dir: /work
    tty: true
    # ports:
    # - 8000:8000
    # environment:
    # command: /bin/sh -c "while sleep 1000; do :; done"
