version: "3"
services:
  python-dev:
    container_name: python-dev
    build:
      context: ..
      dockerfile: .devcontainer/alpine.Dockerfile
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      # - ~/.ssh:/~/.ssh
      - ..:/workspace


        # image: sdator/seed
    # ports:
    # - 8000:8000
    # command: sleep infinity
    # environment:
    # Django web框架需要用到
    # DJANGO_SETTINGS_MODULE: tweeter3.settings.devcontainer
