version: "3"
services:
  py-dev:
    container_name: py-dev
    image: sdator/py
    build:
      dockerfile: .devcontainer/alpine.Dockerfile
      context: ..
    volumes:
      # - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:cached
      - ..:/workspace:cached
    # ports:
    # - 8000:8000
    # environment:
    command: /bin/sh -c "while sleep 1000; do :; done"
