version: '3'
services:
  asddd:
    container_name: python-dev
    # image: sdator/seed
    build: 
      context: ..
      dockerfile: .devcontainer/docker.pl
    # ports:
      # - 8000:8000
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
      - ..:/workspace
    # command: sleep infinity
    # environment:
      # Django web框架需要用到
      # DJANGO_SETTINGS_MODULE: tweeter3.settings.devcontainer
