version: "3"
services:
  dev-py:
    container_name: dev-py
    image: dev:py
    build:
      dockerfile: .devcontainer/alpine.Dockerfile
      context: ..
      args:
        USERNAME: vscode
    volumes:
      # - ~/.gitconfig:/root/.gitconfig
      # - ~/.ssh:/home/vscode/.ssh:cached
      # - ..:/workspace:cached
      - /mnt/d/Git/PY:/workspace:cached
    user: vscode
    # working_dir: /workspace
    tty: true
    # ports:
    # - 8000:8000
    # environment:
    # command: /bin/sh -c "while sleep 1000; do :; done"
