name: Build CI
on:
  push:
    paths:  # 当一下目录发生推送的时候触发
      - './wow/**'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup PY
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
    - name: Install and Build
        working-directory: ./wow # 指定工作目录
        run: |
            pip install pyinstaller # 打包exe
            pip install aiohttp     # 异步http通信
            pyinstaller -F -w 大脚插件自动更新_异步.py -i wow.ico
